### ISSUE TITLE
Unable to resolve domain name for www.pagesjaunes.fr

### ISSUE THREAD

**Issue by aleraillersol** [ssllabs/ssllabs-scan#868]
Hi,

We are getting error "Unable to resolve domain name" both from website or api, while it was working before, and resolution is OK with common DNS resolver.
Impacted URLs : 
www.pagesjaunes.fr
www.cd.pagesjaunes.fr

Issue was intermittent since more than a month, and (almost) permanent since 26/11/2021
Any idea what is the problem here ?

**Comment by aleraillersol** [comment]
Up !
Still facing this issue.

**Comment by naumanshah03** [comment]
Network team is looking into this issue.

In the mean time please use dev.ssllabs.com,
- https://dev.ssllabs.com/ssltest/analyze.html?d=www.pagesjaunes.fr&hideResults=on
- https://dev.ssllabs.com/ssltest/analyze.html?d=www.cd.pagesjaunes.fr&hideResults=on

**Comment by naumanshah03** [comment]
Hi @aleraillersol 

Issue from the network side has been resolved and the scanning for the domain is working now

- https://www.ssllabs.com/ssltest/analyze.html?d=www.pagesjaunes.fr&hideResults=on&ignoreMismatch=on&latest
- https://www.ssllabs.com/ssltest/analyze.html?d=www.cd.pagesjaunes.fr&latest

**Comment by palmbeachcuisine** [comment]
Not resolved. seeing Unable to resolve domain name when testing domain palmbeachcuisine.com
