### ISSUE TITLE
String index out of range: -1

### ISSUE THREAD

**Issue by fsahler** [ssllabs/ssllabs-scan#888]
If I enter "wildcard.datev.de" as hostname, I get the message "String index out of range: -1" as result.

**Comment by naumanshah03** [comment]
This issue is acknowledged and fixed in 2.1.11. Same was reported in #890 
Now it will result in  `Unable to resolve domain name` error

https://dev.ssllabs.com/ssltest/analyze.html?d=wildcard.datev.de
2.1.11 is now available on dev.ssllabs.com and soon it will be available on www.ssllabs.com

Regards,
Nauman Shah

**Comment by blakjaknz** [comment]
> 

Using the public instance i'm still seeing this error, the server i'm trying to test appears to be a DNS stack (CNAME -> CNAME -> A) and I can test the A but I can't test either CNAME, I instead get the same 'String index out of range: -1' error. So this is a related but different issue; the DNS records _are_ present but either SSLLabs can't resolve them, or, they're not coping with stacked CNAMES?
