### ISSUE TITLE
IPv6: Unable to connect to server over IPv6 address

### ISSUE THREAD

**Issue by adymorz** [ssllabs/ssllabs-scan#940]
I tried several websites (not related to each other), on all only the IPv4 connection succeeds on testing, but not the IPv6 one.

https://www.ssllabs.com/ssltest/analyze.html?d=adrian.dymorz.ch
https://www.ssllabs.com/ssltest/analyze.html?d=opsone.ch
https://www.ssllabs.com/ssltest/analyze.html?d=heise.de

I spent some time to figure out the issues on the server I tested first, before I thought about it could be an issue on the test code side.

**Comment by naumanshah03** [comment]
Hi @adymorz 

We are raising this issue with our network team to check for IPv6 resolution. Can expect a fix soon for it.

@catharsis71 Just to bring it to your notice we have updated the production to 2.2.0 and that is the latest version of it whereas our dev is running 2.1.10

Regards,
Nauman Shah

**Comment by naumanshah03** [comment]
Hi @adymorz 

Please check now this issue has been resolved. Hence closing this
Feel free to reopen if you see it again

Regards,
Nauman Shah

**Comment by paulchen** [comment]
@naumanshah03 while the hosts mentioned by OP seem to be working now, there are others that still don't:

https://www.ssllabs.com/ssltest/analyze.html?d=rueckgr.at
https://www.ssllabs.com/ssltest/analyze.html?d=cloud.huntu.at

For both hosts, IPv4 works completely fine. In contrast, IPv6 fails with the error message "Unable to connect to the server".

The checks stopped working at some time between 2023-09-07 and 2023-09-10.

**Comment by paulchen** [comment]
> https://www.ssllabs.com/ssltest/analyze.html?d=rueckgr.at
> https://www.ssllabs.com/ssltest/analyze.html?d=cloud.huntu.at

Meanwhile, the checks for both hosts started working again, both IPv4 and IPv6 are now fine. Thanks for fixing!
